site_name: MkDocs Plugins
site_url: "https://oprypin.github.io/mkdocs-same-dir"
repo_url: "https://github.com/oprypin/mkdocs-same-dir"
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

extra_javascript:
  - assets/script.js

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - def_list
  - toc:
      permalink: "#"

nav:
  - mkdocstrings-crystal: /mkdocstrings-crystal/
  - section-index: /mkdocs-section-index/
  - literate-nav: /mkdocs-literate-nav/
  - gen-files: /mkdocs-gen-files/
  - same-dir: README.md
